### ISSUE TITLE
⚠️The link to Password Reset has issues

### ISSUE THREAD

**Issue by deejinng** [CA-MKSingh/image-portal#1]
![Screenshot_20221221-221208](https://user-images.githubusercontent.com/107402108/209003982-bcab7d28-9dae-4612-8a72-d6869d4c8325.png)

As you can see: `http://https//`image-portal.vercel.app/password/reset/...

And as result of that this happens even after I corrected the link:

![Screenshot_20221221-221311](https://user-images.githubusercontent.com/107402108/209004228-fcd054fb-9470-479c-9eaf-3cdf5ccab1eb.png)

# Awesome project by the way ✨🚀

**Comment by MKSinghDev** [comment]
Currently, there is no route for handling the password reset link. That's why even after correction that isn't working.

However  `http://https://` can be fixed by changing the `env variable` alongwith few tweaks in settings.

**Comment by MKSinghDev** [comment]
One more update, backend isn't working properly. Since, heroku has stopped their free tier so I'm exploring some alternative. I found some options but they have lot of limitation.

It will run properly locally on your system (except password reset link).

**Comment by deejinng** [comment]
You did a very great job by the way 🚀✨

Seeing Next.js with Django is amazing combo ✨

Happy Coding ✨
